version: '3'

services:
    # nest:
    #     build:
    #         context: ./nest
    #     tty: true
    #     working_dir: /opt/nest
    #     expose:
    #         - '3001'
    #     depends_on:
    #         - db

    # next:
    #     build:
    #         context: ./next
    #     tty: true
    #     working_dir: /opt/next
    #     expose:
    #         - '3000'
    #     depends_on:
    #         - db
    #         - nest

    db:
        image: postgres:16
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - database:/var/lib/postgresql/data:delegated
        expose:
            - '5432'
        ports:
            - "5432:5432"
        restart: always

    # nginx:
    #     container_name: proxy_nginx
    #     depends_on:
    #         # - nest
    #         - db
    #     image: nginx:latest
    #     ports:
    #         - '80:80'
    #     volumes:
    #         - ./nginx:/etc/nginx/conf.d
    #         - ./static:/var/www/static
    #     restart: always

volumes:
    database:
